### ISSUE TITLE
Open specific accordion on page load based on url hash value

### ISSUE THREAD

**Issue by maartenhunink** [philbuchanan/Accordion-Blocks#105]
I have a couple of accordions on one page and would like to be able to link to that page and have a specific accordion open based on the url.

I tried achieving this by detecting the `location.hash` and setting the initially-open value of that item to true. 

`$('#'+hash).parent().data({'initially-open' : true);`

This resulted in the the header from being 'open' but the content was still hidden underneath. 

I then went a different route and tried triggering the 'hashchange' event on page load, since I saw you plugin supports it. Hoping this would open up the accordion defined in the hash. But this didn't seem to do anything. I might be doing something wrong, but it seemed like the item.id in the onhashchange function was always undefined. 

What do you think is the easiest approach to achieve this effect? 

Thank you for any suggestions, and thanks for the useful plugin.

**Comment by philbuchanan** [comment]
The plugin does support opening specific accordions based on the hash. The key is you need to enter a specific "HTML anchor" in the "Advanced" settings in the accordion settings sidebar:

<img width="266" alt="Screen Shot 2021-01-27 at 1 04 47 PM" src="https://user-images.githubusercontent.com/1783595/106034082-72ae6e00-60a0-11eb-90fb-90f415e6e754.png">

This will then allow you to add a hash matching that value to the URL, e.g. `https://example.com/path/#accordion-two`.

**Comment by maartenhunink** [comment]
Wonderful! Works like a charm. Thank you for the quick reply and I appologise for not having found this solution myself.
