### ISSUE TITLE
Accordions are being assigned the same ID

### ISSUE THREAD

**Issue by l00sed** [philbuchanan/Accordion-Blocks#114]
Saw you released some changes for version 1.3.1
I'm having an issue where my accordions are all assigned the same ID
![image](https://user-images.githubusercontent.com/23065167/111018534-55e7a480-8387-11eb-8a2f-5fd93f5d1101.png)
![image](https://user-images.githubusercontent.com/23065167/111018550-74e63680-8387-11eb-935a-4af49f7f2252.png)

**Comment by l00sed** [comment]
Using:
WordPress 5.7
PHP 7.3.5

**Comment by l00sed** [comment]
Consequently, whenever I open/close one accordion, it's always opening or closing the first instance of an accordion. Also, all subsequent accordions from the first are appearing empty... It's become quite unusable.

I saw something using window.location.hash (maybe to generate IDs?) and I did console.log(window.location.hash) which returned "" (an empty string)

**Comment by philbuchanan** [comment]
The latest version uses the post ID and an instance ID of the block to generate the accordion item IDs. Looking at your IDs, they are much longer than I would ever expect to see. I'm not sure where they came from. 

What is the ID of your post? And how many blocks do you have on the page?

**Comment by l00sed** [comment]
Hey, thanks for addressing this so quickly.
I verified the post ID in the database:
11482997235265772

Which is indeed quite long. I was trying to do something clever that didn't pan out, that's why they're super high.
Could that be causing an issue with how the ID is chosen or incremented for each accordion?
![image](https://user-images.githubusercontent.com/23065167/111082337-1c757d00-84de-11eb-99ac-98a5083c5956.png)

**Comment by philbuchanan** [comment]
In theory the length of the post ID shouldn't make a difference. The odd part is that the post ID ends in `772`, but the accordion item IDs end in `7730`. I would expect to see them with `772` then then instance ID, something like: `...7721`, `...7722`, `...7723`, etc. The instance ID gets appended to the number, not added to it.

Would you be able to provide the editor HTML code for that page? You can get that by switching to the "Code editor", then selecting all and copying and pasting.

**Comment by l00sed** [comment]
```
<!-- wp:columns {"align":"full"} -->
<div class="wp-block-columns alignfull"><!-- wp:column {"width":"66.66%"} -->
<div class="wp-block-column" style="flex-basis:66.66%"><!-- wp:shortcode -->
[todo_list]
<!-- /wp:shortcode -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657730} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657730" class="c-accordion__title js-accordion-controller" role="button">Accordion 1</h2><div id="ac-114829972352657730" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 1</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:pb/accordion-item --></div></div>
<!-- /wp:group -->

<!-- wp:group -->
<div class="wp-block-group"><div class="wp-block-group__inner-container"><!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657730} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657730" class="c-accordion__title js-accordion-controller" role="button">Accordion 2</h2><div id="ac-114829972352657730" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 2</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:pb/accordion-item --></div></div>
<!-- /wp:group --></div>
<!-- /wp:column -->

<!-- wp:column {"width":"33.33%"} -->
<!-- /wp:column --></div>
<!-- /wp:columns -->
```

**Comment by l00sed** [comment]
Originally, I had copied some content that was nested in accordion blocks from the Gutenberg editor of another site directly into the Gutenberg editor of this site. The other site's accordions are working fine; but it's using WP 5.6 (I think) and, like I mentioned, this site was just upgraded to 5.7.

I thought, perhaps it could be some weird issue with stale data that was carried over in the clipboard; but I tried creating a new post from scratch as well as deleting all the accordions. Observed this behavior each time.

**Comment by philbuchanan** [comment]
When I paste that code into a new post of a clean install of WordPress, it works as expected, remapping the accordion IDs to match my post ID and instance IDs. I'm really not sure what is going on with your install.

Can you try adding one new temporary accordion item (not copying/duplicating) and then saving the post to see if at least that _new_ accordion item works?

**Comment by l00sed** [comment]
Added a new post (ID = 11482997235265792). Created 5 new accordions. Code editor:
```
<!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657920} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button">Accordion 1</h2><div id="ac-114829972352657920" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 1</p>
<!-- /wp:paragraph -->
</div>
</div>
<!-- /wp:pb/accordion-item -->

<!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657920} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button">Accordion 2</h2><div id="ac-114829972352657920" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 2</p>
<!-- /wp:paragraph -->
</div>
</div>
<!-- /wp:pb/accordion-item -->

<!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657920} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button">Accordion 3</h2><div id="ac-114829972352657920" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 3</p>
<!-- /wp:paragraph -->
</div>
</div>
<!-- /wp:pb/accordion-item -->

<!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657920} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button">Accordion 4</h2><div id="ac-114829972352657920" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 4<div class="tooltip-shift-plug">Paragraph</div></p>
<!-- /wp:paragraph -->
</div>
</div>
<!-- /wp:pb/accordion-item -->

<!-- wp:pb/accordion-item {"scroll":true,"uuid":114829972352657920} -->
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item no-js" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button">Accordion 5</h2><div id="ac-114829972352657920" class="c-accordion__content"><!-- wp:paragraph -->
<p>accordion 5</p>
<!-- /wp:paragraph -->
</div>
</div>
<!-- /wp:pb/accordion-item -->
```

When I go to the post page, Accordions 1, 4 and 5 seem to work as expected. However, Accordions 2 and 3 control Accordion 1:

![test](https://user-images.githubusercontent.com/23065167/111184153-0d96d500-8587-11eb-812b-3116bf3d5897.gif)

Here are the contents of the <article> tag after inspecting the published page:

```
<article class="post-11482997235265792 surgicorps_trip type-surgicorps_trip status-publish entry" aria-label="Accordions Tester" itemscope="" itemtype="https://schema.org/CreativeWork"><header class="entry-header"><h1 class="entry-title" itemprop="headline">Accordions Tester</h1>
<p class="entry-meta"><time class="entry-time" itemprop="datePublished" datetime="2021-03-15T12:03:12-04:00">March 15, 2021</time> by <span class="entry-author" itemprop="author" itemscope="" itemtype="https://schema.org/Person"><a href="http://surgicorps.local/author/danshift/" class="entry-author-link" rel="author" itemprop="url"><span class="entry-author-name" itemprop="name">Daniel Tompkins</span></a></span>  <a class="post-edit-link" href="http://surgicorps.local/wp-admin/post.php?post=11482997235265792&amp;action=edit">(Edit)</a></p></header><div class="entry-content" itemprop="text">
<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item is-read" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button" tabindex="0" aria-controls="ac-114829972352657920" aria-expanded="false">Accordion 1</h2><div id="ac-114829972352657920" class="c-accordion__content" style="display: none;" hidden="hidden">
<p>accordion 1</p><div class="tooltip-shift-plug">Paragraph</div><p></p>
</div></div>



<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item is-read" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button" tabindex="0" aria-controls="ac-114829972352657920" aria-expanded="false">Accordion 2</h2><div id="ac-114829972352657920" class="c-accordion__content">
<p>accordion 2</p><div class="tooltip-shift-plug">Paragraph</div><p></p>
</div></div>



<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item is-read" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657920" class="c-accordion__title js-accordion-controller" role="button" tabindex="0" aria-controls="ac-114829972352657920" aria-expanded="false">Accordion 3</h2><div id="ac-114829972352657920" class="c-accordion__content">
<p>accordion 3</p><div class="tooltip-shift-plug">Paragraph</div><p></p>
</div></div>



<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item is-read" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-114829972352657940" class="c-accordion__title js-accordion-controller" role="button" tabindex="0" aria-controls="ac-114829972352657940" aria-expanded="false">Accordion 4</h2><div id="ac-114829972352657940" class="c-accordion__content" style="display: none;" hidden="hidden">
<p>accordion 4</p>
</div></div>



<div class="wp-block-pb-accordion-item c-accordion__item js-accordion-item is-read" data-initially-open="false" data-click-to-close="true" data-auto-close="true" data-scroll="true" data-scroll-offset="0"><h2 id="at-1148299723526579200" class="c-accordion__title js-accordion-controller" role="button" tabindex="0" aria-controls="ac-1148299723526579200" aria-expanded="false">Accordion 5</h2><div id="ac-1148299723526579200" class="c-accordion__content" style="display: none;" hidden="hidden">
<p>accordion 5</p><div class="tooltip-shift-plug">Paragraph</div><p></p>
</div></div>
</div><footer class="entry-footer"></footer></article>
```

So it assigned *20 *20 *20 *40 *200

**Comment by l00sed** [comment]
Interestingly, if I preview the post, it will set all accordions to the *20 post-fixed IDs; but if I view the canonical URL of the post, it will set the *20, *20, *20, *40, *200 post-fix pattern.

Then, after updating the post, the canonical showed *20, *20, *20, *20, *40.

If I refresh the edit page, then update again, the canonical shows *20, *20, *20, *20, *20. So it seems like it's progressively reassigning the id to that base post-fix somehow...

**Comment by l00sed** [comment]
I'm new to WordPress development, and I don't know whether WordPress creates the ID of the block automatically based on the post ID, or if you've specified how that should happen.

If your plugin is setting that ID, could you point me to the file + line # where I can find the assignment? Maybe that will help me get to the bottom of this.

**Comment by philbuchanan** [comment]
None of this makes much sense to me. I can't reproduce locally or figure out why your site isn't returning a proper instance ID. Unfortunately I'm not sure how much more help I'll be able to offer.

[Here are the relevant lines of code for generating the accordion item's ID.](https://github.com/philbuchanan/Accordion-Blocks/blob/94943ef9a3102b0b59a196b48b34435e577504c9/src/block/edit.js#L70-L81)

**Comment by l00sed** [comment]
I cherry-picked a commit (6eca4896b9538d28805c454c1f4be39f54aa3ec2) that included a couple console.log's in `build/index.js` and observed "set new id" was logging out the same (post_id + "0" post-fixed) for each accordion.

I rolled back to release 1.1.6 and it's working again on 5.7
I think the issue definitely lies somewhere in how the `uuid` assigned. Maybe with the info you provided, I'll be able to pin-point it.

I did try the plugin on a fresh 5.7 build and it wasn't having these issues; so it's likely something related to my super-long IDs or something particular to the other plugins or settings for this site.

**Comment by l00sed** [comment]
Seems like the root of the issue could be in how this is returning:
`const instanceId = useInstanceId(AccordionItemEdit);`

Seems like the instance might have been returning `false` or `0`

**Comment by philbuchanan** [comment]
[`useInstanceId`](https://github.com/WordPress/gutenberg/tree/trunk/packages/compose/src/hooks/use-instance-id) is a WordPress/Gutenberg thing. Unfortunately I have no control over it.

**Comment by philbuchanan** [comment]
If you can figure out in what circumstances it is _not_ retuning a unique instance ID, I can file a bug with WordPress.
