### ISSUE TITLE
"Load scripts and styles globally" is not applied until unset and reset

### ISSUE THREAD

**Issue by kub1x** [philbuchanan/Accordion-Blocks#137]
Hey, I used Accordion-Blocks as a HTML source in my sidebar, since there was no other way. After update, this side menu broke. I seeked into Admin of the plugin and found the one and only checkbox - thanks for it! Thoughtful. It was checked but the styles and js wasn't being applied globally until I "unchecked - saved - checked - saved" it.

**Comment by philbuchanan** [comment]
@kub1x Should be fixed in v1.3.5 which I just released.
