### ISSUE TITLE
Creating 2 Accordions on the same page

### ISSUE THREAD

**Issue by RexJaguarius** [philbuchanan/Accordion-Blocks#144]
I need to create 2 separate accordions on the same page, but I can't seem to determine how to do it. Can anyone help?

**Comment by philbuchanan** [comment]
You can simply add two `Accordion Item` blocks on a page. The same way you would add multiple paragraph, or heading blocks.

If you want each accordion to _not_ auto close when the other accordion is interacted with, you can wrap the `Accordion Item` blocks in a `Group` block. All `Accordion Item` blocks within a single group will interact with each other, but not interact with other `Accordion Item` blocks on the page.

**Comment by RexJaguarius** [comment]
Thanks Phil! Plugin looks great so far.
