### ISSUE TITLE
Additional block attribute not being added

### ISSUE THREAD

**Issue by landwire** [philbuchanan/Accordion-Blocks#145]
Hi Phil,
First of all thank you for a great plugin!

I have a slight problem though: I am using **blocks.registerBlockType** to add additional attributes to all blocks. Unfortunately this does not work for your block. I am using the following code:

```
const addLayoutControlAttribute = (settings, name) => {
	// Use Lodash's assign to gracefully handle if attributes are undefined
	settings.attributes = assign(settings.attributes, {
		layoutSize: {
			type: 'string',
			default: layoutControlOptions[2].value, //medium
		},
	});

	if (name === 'pb/accordion-item') {
		console.log('filter is running!');
	}

	console.log(name);
	console.log(settings);
	return settings;
};

addFilter(
	'blocks.registerBlockType',
	'block-layout/attribute-layoutSize',
	addLayoutControlAttribute
);
```

But for some reason this filter does not seem to run and therefore the attributes are obviously are not being saved. Do you have any idea why not? It works with all core blocks.

**Comment by landwire** [comment]
On the image below you can see the attribute and filter working on core blocks:

<img width="762" alt="Screenshot 2021-08-17 at 14 24 07" src="https://user-images.githubusercontent.com/1001202/129725107-7f40f9b9-bd0e-44f9-a1f0-d0ed00dcdf71.png">

**Comment by landwire** [comment]
Ok, seems to be a known issue: 
https://github.com/WordPress/gutenberg/issues/9757

I have used the workaround from https://github.com/WordPress/gutenberg/issues/9757#issuecomment-486088850 and it seems to work for now.

**Comment by philbuchanan** [comment]
Given this seems to be a bug with Gutenberg itself, I'm going to close for now.
