### ISSUE TITLE
In Mobile, all accordions are open by default - how do I fix?

### ISSUE THREAD

**Issue by JennChing** [philbuchanan/Accordion-Blocks#158]
Hi! I'm a total newbie and just used your plug-in to create my first accordion blocks! I noticed that when I open the page on desktop, all the accordions are closed by default, but in the mobile view, they are all open by default.  How do I fix this?

**Comment by philbuchanan** [comment]
What you described is not the default behaviour of this plugin. A few things to look at:

- Confirm you are using this plugin (and not another accordion plugin which may operate in a different way)
- Make sure your theme or another plugin isn't causing the unexpected behaviour (deactivate all plugins and switch to a default theme, e.g. Twenty Twenty Two).
