### ISSUE TITLE
title and category properties are missing

### ISSUE THREAD

**Issue by htmgarcia** [philbuchanan/Accordion-Blocks#163]
Trying to access the block through a third party block (in this case PublishPress Blocks) returns an error in browser console: 
`The block "pb/accordion-item" must have a title.`

Adding `title` and `category` at the same level of `icon` may solve the issue: https://github.com/philbuchanan/Accordion-Blocks/blob/master/src/block/settings.js#L13

Related documentation: https://developer.wordpress.org/block-editor/reference-guides/block-api/block-registration/

Regards

**Comment by philbuchanan** [comment]
Sorry for the delayed response.

> The block "pb/accordion-item" must have a title.

This error specifically refers to the title of the accordion item in the editor. Each accordion item needs to have text that is used to trigger the open/close of the item.

The documentation you are referring to relates to the block title, which is [specified in the `block.json` file](https://github.com/philbuchanan/Accordion-Blocks/blob/master/block.json#L4).
