### ISSUE TITLE
Change the "+" to "-" when the accordion is expanded to show different state - NOT CORRECT TO RELEASED VER

### ISSUE THREAD

**Issue by jcamp** [philbuchanan/Accordion-Blocks#165]
It would be useful from a user interface point of view to Change the "+" to "-" when the accordion is expanded to show different state. The symbol used when "open" and "closed" would be good if this could be changed or in the config as well?

**Comment by philbuchanan** [comment]
Accordions [currently do show the "-" when open](https://github.com/philbuchanan/Accordion-Blocks/blob/master/src/block/index.scss#L77) and the "+" when closed. You can easily change the specific styling of opened vs. closed items via CSS. The intention is to keep the plugin as simple as possible and allow customization via CSS.

**Comment by jcamp** [comment]
Thanks for the reply, but I use the bog standard plugin and the def do not show "+" and "-"?

I have many accordions on a page does that matter?

**Comment by jcamp** [comment]
this is the index.css file from wordpress repo:

.c-accordion__item.is-selected{border-bottom:1px solid var(--wp-admin-theme-color)!important}
