### ISSUE TITLE
Warning: This plugin hasn’t been tested with the latest 3 major releases of WordPress

### ISSUE THREAD

**Issue by Vilasamuni** [philbuchanan/Accordion-Blocks#176]
The Wordfence Security plugin is warning me that this plugin has been abandoned and poses a security risk:
The Plugin "Accordion Blocks" appears to be abandoned (updated February 7, 2022, tested to WP 5.9.9). 

The [plugin page on WordPress.org](https://wordpress.org/plugins/accordion-blocks/) shows a warning:
This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.

**Comment by philbuchanan** [comment]
Not abandoned, just not in need of updates. And given it is free, I don't devote much time to it. I do use it on dozens of my own sites running most recent version of WordPress without issue.

**Comment by Vilasamuni** [comment]
Thanks for clarifying :+1:
