### ISSUE TITLE
CSS examples in Wiki?

### ISSUE THREAD

**Issue by glorious1** [philbuchanan/Accordion-Blocks#18]
I'm really liking this little plugin, but the style isn't all there for me.  I appreciate that you listed the classes to use for CSS, but for the CSS-challenged among us, it would be nice to have some examples to copy and edit.  I still can't figure out how to use disclosure triangles instead of +/-, but that's minor.

For example, here is some CSS I figured out by trial and error to:
- add a second +/- symbol to the left of the title so it is more obvious to the reader
- shade the title line and adjust margins appropriately so items aren't at edge of shading
- indent the content

`/* 
Add the +/- before the accordion item title
(occurs on right margin of page already), with a right margin
 */
.c-accordion__title::before {
    position: relative;
    top: 50%;
    right: 0;
    content: "+";
    color: #777;
    font-weight: 300;
    -webkit-transform: translateY(-50%);
    transform: translateY(-50%);
    margin-right: 0.5em;
}

.is-open .c-accordion__title::before {
    content: "\2212";
}

/* Shade the title line */
.c-accordion__title {
    background-color: #f2f2f2;
    padding: 0.2em;
}

/* Bring the right +/- in so it's not on edge of shading */
.c-accordion__title::after {
    margin-right: 0.5em;
}

/* Indent the content beneath title */
.c-accordion__content {
    margin-left: 2em;
}`

**Comment by philbuchanan** [comment]
The styles are deliberately left sparse, so accordions will better blend with the users existing site styles.

You can add triangles before the titles like this:

```css
.c-accordion__title:before {
    content: "\25BC";
}

.is-open .c-accordion__title:before {
    content: "\25B2";
}
```

I've thought about adding a bunch of style options to the plugin documentation but I just don't have the time to devote to creating a diverse set. If you come up with some that work well, please add them to the [plugin support forum](https://wordpress.org/support/plugin/accordion-blocks/).
