### ISSUE TITLE
Add Screenshots for WordPress Plugin Repo

### ISSUE THREAD

**Issue by mrwweb** [philbuchanan/Accordion-Blocks#21]
When evaluating this plugin, it would be really helpful to see the block UI in the editor as well as the output with Twenty Nineteen or Twenty Twenty. While you're at it, maybe throw together a banner image showing the block UI too!

**Comment by bobbingwide** [comment]
![accordion-blocks-pb-accordion-item-example](https://user-images.githubusercontent.com/2474435/70990908-69418c80-20be-11ea-8989-fe433f91a5ad.jpg)

Note: In this version the toolbar icons are not displayed.
