### ISSUE TITLE
Request: Consider site-wide options and setting defaults

### ISSUE THREAD

**Issue by mrwweb** [philbuchanan/Accordion-Blocks#22]
Right now, it looks like all the options for the block have to be customized individually on each block. I think this could be greatly improved to make editor's lives easier and sites more consistent.

I would recommend completely removing the offset block setting and make that a universal site-wide setting. For all other block settings, it would be really nice to be able to set global default values in the case that I want to change the defaults provided by the plugin.

**Comment by philbuchanan** [comment]
I agree this would be very useful. I just need to find the time to actually do the work...
