### ISSUE TITLE
Toolbar icons not displayed

### ISSUE THREAD

**Issue by bobbingwide** [philbuchanan/Accordion-Blocks#27]
In my editor ( WordPres 5.3.1, Gutenberg 7.0.0 ) I don't see any icons for h1,h2,h3,h4 and button
For screenshot see #21 

Also. There's a typo in Scroll Pixel Offset
![accordion-blocks-pb-accordion-item-settings](https://user-images.githubusercontent.com/2474435/70993195-62694880-20c3-11ea-866e-8e1e57d51ae9.jpg)

PS. I've added the block to my WordPress blocks reference. https://blocks.wp-a2z.org/block/accordion-item-pb-accordion-item/

**Comment by philbuchanan** [comment]
I'm not seeing the issue with missing `h1`, `h2` etc. Gutenberg plugin version 7.1.0, WordPress 5.3.2. Maybe a conflict with another plugin?

I will fix the typo. Thank you.
