### ISSUE TITLE
Add function: FAQ Schema / Rich Snippet

### ISSUE THREAD

**Issue by frankfurth** [philbuchanan/Accordion-Blocks#30]
Is it possible to add function for automatic faq schema?
https://developers.google.com/search/docs/data-types/faqpage

**Comment by philbuchanan** [comment]
The challenge with adding FAQ structured data markup is that not all accordions are used specifically for FAQs. I myself often use them to visually hide additional, non-critical information.

**Comment by philbuchanan** [comment]
I have decided not to implement this functionality.
