### ISSUE TITLE
Issue/Feature: More than one post displayed  

### ISSUE THREAD

**Issue by rikrog** [philbuchanan/Accordion-Blocks#31]
Hello Phil

Spotted an issue if two posts are displayed in Wordpress.. The accordion controls fail. 

I think it is the repeating of the accordion ID 

Would it be possible to add a unique ID No. added to id= / aria-controls= for each accordion tab ? I ..think.. that might fix this. 

Thanks!

**Comment by philbuchanan** [comment]
Interesting. I assume this is happening on your posts archive pages and you are displaying the full post content, not just an excerpt? 

I'll have to look into alternatives for generate the IDs.

**Comment by rikrog** [comment]
You assume right. Thanks for looking into it!

**Comment by philbuchanan** [comment]
@rikrog This should be fixed in the next version of the plugin I am currently working on, set to go out in the next week or two hopefully.

Unfortunately it will only fix _new_ accordion items since I cannot update the ID of all existing accordion items. Existing ones will still exhibit the issue.

**Comment by rikrog** [comment]
Excellent. Thanks.
