### ISSUE TITLE
Accordion blocks being flagged as "invalid content" and can’t be edited in multisite install

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/Accordion-Blocks#40]
Only network super-admins are able to see and edit the accordion item content.

[See this support thread](https://wordpress.org/support/topic/weird-behavior-on-multisite/).

**Comment by philbuchanan** [comment]
This seems to have to do with who has the `unfiltered_html` permission. In multisite installs, the `Editor` role **does not** have that permission. In regular installs, the `Editor` roles does, however the `Author` role does not.

The `tabindex` and `aria-controls` attributes are being stripped during the `save` function when anyone without the `unfiltered_html` permission saves the post causing the "invalid content" error if the next user to view the page has that permission (and vice-versa).

**Comment by emilio-pro** [comment]
This will probably fix it:
https://gist.github.com/jazzsequence/4f16932fdc5980c0af43dbdc9bf9aac4
However, it might be risky to allow just any editor to use unfiltered_html as explained by Automattic here: 
https://wordpress.org/plugins/unfiltered-mu/

**Comment by philbuchanan** [comment]
@emilio-pro I'd like to avoid opening security holes. That solution also won't resolve the issue for all users as anyone below the `Editor` role still won't have `unfiltered_html` permission (e.g. `Author`).

My current plan is to remove the attributes (`tabindex` and `aria-controls` are not supported by WordPress—[see the full list of supported attributes here](https://github.com/WordPress/WordPress/blob/master/wp-includes/kses.php#L2329-L2339)) from the save function and simply add those via JS on the frontend.
