### ISSUE TITLE
"Duplicate Block" causes clicking on duplicate to open original block

### ISSUE THREAD

**Issue by slambert** [philbuchanan/Accordion-Blocks#47]
First - thank you @philbuchanan for making this.

I often group blocks and duplicate them in order to quickly make a layout on the page. I've noticed when using the accordion block that if I duplicate it and click to expand the duplicate, it opens the original. I'm assuming it's because an ID is created that is also duplicated. 

I understand if this is a low priority, just wanted to bring it to your attention as I didn't see it among open or closed issues.

Thanks again!

**Comment by philbuchanan** [comment]
This looks like a bug. I’ll have to do some digging to see how I can resolve it. Thanks for pointing it out.

**Comment by philbuchanan** [comment]
Should be resolved in v1.1.1 which was just released. Let me know if you still see the issue. 

One note: for any existing blocks that are broken, you will need to re-save the post/page for the new ID to be applied.
