### ISSUE TITLE
Consider using a caret instead of a plus sign

### ISSUE THREAD

**Issue by druxstr** [philbuchanan/Accordion-Blocks#77]
UX research on accordion icons suggests that the caret is a better signifier :

> The caret icon most clearly indicated to users that it would open an accordion in place, rather than linking directly to a new page [...] Use a caret icon to designate an accordion, whether on desktop or mobile — our study found that of the standard set of icons used in this context, only the caret performed better than either no icon or a nonsense icon at indicating that than it was an accordion.

See : https://www.nngroup.com/articles/accordion-icons/

**Comment by philbuchanan** [comment]
Thanks for the suggestion. 

The study was specifically testing accordions in the context of mobile navigation. It doesn't mention if there is a correlation between accordions in navigation (where there is a default expectation that you will be navigating to another page) and accordions in content. So I'm not sure the results are directly applicable to this plugin. Additionally, the different between the performance of the caret and plus icons was relatively low—49% expected a new page with the plus, vs. 47% with the caret. The statistically significant difference was related to icon vs. no icon or nonsense icon.

Given that the icon can be easily changed via CSS, and that making this change would affect all existing installs of the plugin, I likely will not be implementing this.
