### ISSUE TITLE
Limit ability to insert one accordion item inside another

### ISSUE THREAD

**Issue by philbuchanan** [philbuchanan/Accordion-Blocks#79]
If there is no easy way to do this, perhaps presenting the user with a warning that they have inserted an accordion item inside another would help.

**Comment by philbuchanan** [comment]
This is, of course, at odds with #37. Perhaps nesting should work/be allowed, but if a user _does_ nest an accordion inside another accordion, we provide a warning of some sort so they aren't confused by the behaviour of nested accordions.

**Comment by audiovisuel-uqam** [comment]
perhaps this could be a quick hotfix, and #37 an eventual feature...
