### ISSUE TITLE
PHP Parse error in 1.2.0 release

### ISSUE THREAD

**Issue by mikemarlett** [philbuchanan/Accordion-Blocks#97]
PHP Parse error:  syntax error, unexpected ')' in /data/wp/content/html/ms/wp-content/plugins/accordion-blocks/accordion-blocks.php on line 155

There is a comma that needs to come out on line 154.

**Comment by philbuchanan** [comment]
Thanks for reporting @mikemarlett. Should be resolved in v1.2.1. Sorry about the issue.
