### ISSUE TITLE
Non Translatable accordion titles

### ISSUE THREAD

**Issue by geokha** [philbuchanan/Accordion-Blocks#99]
Hello, I've just started using this plugin for a website, but there is one huge bug, when I translate all the content of the page in WPML, the titles of the accordion group still shows in the original language, while the content of the accordion is showing the translated text.
Is there any fix for this or is it a bug?

**Comment by philbuchanan** [comment]
The accordion titles are translatable for me using WPML on a fresh install of WordPress using the Twenty Twenty theme. Perhaps there is another issue/conflict with the site. I'd suggest disabling all other plugins and switching to the default WordPress theme then re-enabling each until you find the issue.

**Comment by w3code1** [comment]
Hi Phil, i have the same issue. The accordion title wont translate. I had deactivaed all other plugins and use the default theme.

**Comment by philbuchanan** [comment]
[Can you try this](https://wpml.org/forums/topic/problem-with-accordion-blocks-phil-buchanan/#post-10236539)?

**Comment by w3code1** [comment]
That worked for me. I had created a wpml-config.xml in my theme directory. You can [implement ](https://wpml.org/documentation/support/language-configuration-files/ )it directly in your plugin.
